import Favicon from '../../public/favicon.ico'
import "./globals.css"

export const metadata = {
  title: 'Bloxbunny',
  description: 'Generated by Next.js',
  icons: [{ rel: 'icon', url: Favicon.src }]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
